function javaleague2(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',Pb='&',gc='.cache.html',db='/',pb='//',fc=':',tb='::',tc='<script defer="defer">javaleague2.onInjectionDone(\'javaleague2\')<\/script>',lb='<script id="',wb='=',cb='?',Ib='Android',yb='Bad handler "',sc='DOMContentLoaded',ec="GWT module 'javaleague2' may need to be (re)compiled",nb='SCRIPT',Sb='Unexpected exception in locale detection, using default: ',Rb='_',Qb='__gwt_Locale',kb='__gwt_marker_javaleague2',ob='base',gb='baseUrl',X='begin',W='bootstrap',fb='clear.cache.gif',vb='content',pc='css/bootstrap-datetimepicker.min.css',oc='css/bootstrap.min.css',nc='css/font-awesome.min.css',rc='css/summernote-bs3.min.css',qc='css/summernote.min.css',ab='end',Nb='es',$b='gecko',_b='gecko1_8',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',hc='gwt/standard/standard.css',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',mc='head',cc='hosted.html?javaleague2',lc='href',Jb='iPad',Hb='iPhone',Xb='ie10',Zb='ie8',Yb='ie9',Cb='iframe',eb='img',Gb='ismobile',U='javaleague2',ib='javaleague2.nocache.js',sb='javaleague2::',Db="javascript:''",ic='link',bc='loadExternalRefs',Mb='locale',Ob='locale=',qb='meta',Fb='moduleRequested',_='moduleStartup',Wb='msie',rb='name',Lb='no',Eb='position:absolute;width:0;height:0;border:none',jc='rel',Vb='safari',hb='script',dc='selectingPermutation',V='startup',kc='stylesheet',jb='undefined',ac='unknown',Tb='user.agent',Ub='webkit',Kb='yes';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}javaleague2=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=K(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a,b){return b in v[a]}
function K(a){var b=u[a];return b==null?null:b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){return navigator.userAgent.indexOf(Hb)>-1||(navigator.userAgent.indexOf(Ib)>-1||navigator.userAgent.indexOf(Jb)>-1)?Kb:Lb};v[Gb]={no:0,yes:1};w[Mb]=function(){var b=null;var c=Nb;try{if(!b){var d=location.search;var e=d.indexOf(Ob);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Pb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=K(Mb)}if(!b){b=m[Qb]}if(b){c=b}while(b&&!J(Mb,b)){var h=b.lastIndexOf(Rb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Sb+a)}m[Qb]=c;return b||Nb};v[Mb]={'default':0,en:1,es:2};w[Tb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Ub)!=-1}())return Vb;if(function(){return b.indexOf(Wb)!=-1&&n.documentMode>=10}())return Xb;if(function(){return b.indexOf(Wb)!=-1&&n.documentMode>=9}())return Yb;if(function(){return b.indexOf(Wb)!=-1&&n.documentMode>=8}())return Zb;if(function(){return b.indexOf($b)!=-1}())return _b;return ac};v[Tb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};javaleague2.onScriptLoad=function(){if(M){r=true;G()}};javaleague2.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:bc,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=cc;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:dc});if(!F()){try{alert(ec);return;var Q=O.indexOf(fc);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+gc}catch(a){return}}var R;function S(){if(!s){s=true;if(!__gwt_stylesLoaded[hc]){var a=n.createElement(ic);__gwt_stylesLoaded[hc]=a;a.setAttribute(jc,kc);a.setAttribute(lc,t+hc);n.getElementsByTagName(mc)[0].appendChild(a)}if(!__gwt_stylesLoaded[nc]){var a=n.createElement(ic);__gwt_stylesLoaded[nc]=a;a.setAttribute(jc,kc);a.setAttribute(lc,t+nc);n.getElementsByTagName(mc)[0].appendChild(a)}if(!__gwt_stylesLoaded[oc]){var a=n.createElement(ic);__gwt_stylesLoaded[oc]=a;a.setAttribute(jc,kc);a.setAttribute(lc,t+oc);n.getElementsByTagName(mc)[0].appendChild(a)}if(!__gwt_stylesLoaded[pc]){var a=n.createElement(ic);__gwt_stylesLoaded[pc]=a;a.setAttribute(jc,kc);a.setAttribute(lc,t+pc);n.getElementsByTagName(mc)[0].appendChild(a)}if(!__gwt_stylesLoaded[qc]){var a=n.createElement(ic);__gwt_stylesLoaded[qc]=a;a.setAttribute(jc,kc);a.setAttribute(lc,t+qc);n.getElementsByTagName(mc)[0].appendChild(a)}if(!__gwt_stylesLoaded[rc]){var a=n.createElement(ic);__gwt_stylesLoaded[rc]=a;a.setAttribute(jc,kc);a.setAttribute(lc,t+rc);n.getElementsByTagName(mc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(sc,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener(sc,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:bc,millis:(new Date).getTime(),type:X});n.write(tc)}
javaleague2();