function javaleague2(){var U='',Cb='" for "gwt:onLoadErrorFn"',Ab='" for "gwt:onPropertyErrorFn"',nb='"><\/script>',cb='#',Kb='&',tc='.cache.html',eb='/',qb='//',bc='135DA603E6E8A8A18F928A2AE9760D66',cc='1470E53BB41A114CE28D606C0CEB07C3',ec='33969D90E58B52BF1DFE2550314C10BC',fc='38826090DAA405FB08ACFABAF5BE4154',gc='410B7995EAB21D6A0A41A2CABBF8E92D',hc='5105B53F9AEAD1EEBB150D8E04B817C2',jc='5B12A34DC4A4096E890FBD9288450048',kc='6252ECF31E065BA5F6267A76D7EA63FC',lc='62D5DD5500C2A91F5623FE9490E328F7',mc='791F63ED46C70527DDF8107DC80360E9',nc='9361A924FA7BAC80D495B67C06CA5174',sc=':',ub='::',Mb=';',Gc='<script defer="defer">javaleague2.onInjectionDone(\'javaleague2\')<\/script>',mb='<script id="',xb='=',db='?',oc='BADA2EA8438CF7DC190C6CF9C3792854',zb='Bad handler "',pc='D09220E8DDE47B72EE12E70D278260A8',Fc='DOMContentLoaded',qc='E38B7D545F7588CBB56A7FF9ED75E413',rc='F23A0381B4A4579C5AB13610DA04FAF9',Lb='GWT_LOCALE=',ob='SCRIPT',Pb='Unexpected exception in locale detection, using default: ',Ob='_',Nb='__gwt_Locale',lb='__gwt_marker_javaleague2',pb='base',hb='baseUrl',Y='begin',X='bootstrap',gb='clear.cache.gif',wb='content',Cc='css/bootstrap-datetimepicker.min.css',Bc='css/bootstrap.min.css',Ac='css/font-awesome.min.css',Ec='css/summernote-bs3.min.css',Dc='css/summernote.min.css',ic='default',dc='en',bb='end',Ib='es',Xb='gecko',Yb='gecko1_8',Z='gwt.codesvr=',$='gwt.hosted=',_='gwt.hybrid',uc='gwt/standard/standard.css',Bb='gwt:onLoadErrorFn',yb='gwt:onPropertyErrorFn',vb='gwt:property',zc='head',_b='hosted.html?javaleague2',yc='href',Ub='ie10',Wb='ie8',Vb='ie9',Db='iframe',fb='img',V='javaleague2',jb='javaleague2.nocache.js',tb='javaleague2::',Eb="javascript:''",vc='link',$b='loadExternalRefs',Hb='locale',Jb='locale=',rb='meta',Gb='moduleRequested',ab='moduleStartup',Tb='msie',sb='name',Fb='position:absolute;width:0;height:0;border:none',wc='rel',Sb='safari',ib='script',ac='selectingPermutation',W='startup',xc='stylesheet',kb='undefined',Zb='unknown',Qb='user.agent',Rb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=U,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:Y});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Z)!=-1||(c.indexOf($)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(_)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(V);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return M(a)}}javaleague2=null;c.gwtOnLoad(C,V,t,B);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:bb})}}
function H(){function e(a){var b=a.lastIndexOf(cb);if(b==-1){b=a.length}var c=a.indexOf(db);if(c==-1){c=a.length}var d=a.lastIndexOf(eb,Math.min(c,b));return d>=0?a.substring(0,d+1):U}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(fb);b.src=a+gb;a=e(b.src)}return a}
function g(){var a=K(hb);if(a!=null){return a}return U}
function h(){var a=n.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(jb)!=-1){return e(a[b].src)}}return U}
function i(){var a;if(typeof isBodyLoaded==kb||!isBodyLoaded()){var b=lb;var c;n.write(mb+b+nb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ob){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return U}
function j(){var a=n.getElementsByTagName(pb);if(a.length>0){return a[a.length-1].href}return U}
function k(){var a=n.location;return a.href==a.protocol+qb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==U){l=h()}if(l==U){l=i()}if(l==U){l=j()}if(l==U&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(rb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(sb),g;if(f){f=f.replace(tb,U);if(f.indexOf(ub)>=0){continue}if(f==vb){g=e.getAttribute(wb);if(g){var h,i=g.indexOf(xb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=U}u[f]=h}}else if(f==yb){g=e.getAttribute(wb);if(g){try{D=eval(g)}catch(a){alert(zb+g+Ab)}}}else if(f==Bb){g=e.getAttribute(wb);if(g){try{C=eval(g)}catch(a){alert(zb+g+Cb)}}}}}}
function J(a,b){return b in v[a]}
function K(a){var b=u[a];return b==null?null:b}
function L(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function M(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var N;function O(){if(!N){N=true;var a=n.createElement(Db);a.src=Eb;a.id=V;a.style.cssText=Fb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:Gb});a.contentWindow.location.replace(t+Q)}}
w[Hb]=function(){var b=null;var c=Ib;try{if(!b){var d=location.search;var e=d.indexOf(Jb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Kb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){var h=n.cookie;var i=h.indexOf(Lb);if(i>=0){var g=h.indexOf(Mb,i);if(g<0){g=h.length}b=h.substring(i+11,g)}}if(!b){b=K(Hb)}if(!b){b=m[Nb]}if(b){c=b}while(b&&!J(Hb,b)){var j=b.lastIndexOf(Ob);if(j<0){b=null;break}b=b.substring(0,j)}}catch(a){alert(Pb+a)}m[Nb]=c;return b||Ib};v[Hb]={'default':0,en:1,es:2};w[Qb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Rb)!=-1}())return Sb;if(function(){return b.indexOf(Tb)!=-1&&n.documentMode>=10}())return Ub;if(function(){return b.indexOf(Tb)!=-1&&n.documentMode>=9}())return Vb;if(function(){return b.indexOf(Tb)!=-1&&n.documentMode>=8}())return Wb;if(function(){return b.indexOf(Xb)!=-1}())return Yb;return Zb};v[Qb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};javaleague2.onScriptLoad=function(){if(N){r=true;G()}};javaleague2.onInjectionDone=function(){q=true;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:$b,millis:(new Date).getTime(),type:bb});G()};I();H();var P;var Q;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(V))){m.location.reload();return}Q=_b;P=U}o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:ac});if(!F()){try{L([Ib,Ub],bc);L([Ib,Sb],cc);L([dc,Sb],ec);L([dc,Wb],fc);L([dc,Yb],gc);L([dc,Ub],hc);L([ic,Sb],jc);L([ic,Wb],kc);L([ic,Ub],lc);L([Ib,Vb],mc);L([dc,Vb],nc);L([ic,Yb],oc);L([Ib,Wb],pc);L([ic,Vb],qc);L([Ib,Yb],rc);P=A[M(Hb)][M(Qb)];var R=P.indexOf(sc);if(R!=-1){B=Number(P.substring(R+1));P=P.substring(0,R)}Q=P+tc}catch(a){return}}var S;function T(){if(!s){s=true;if(!__gwt_stylesLoaded[uc]){var a=n.createElement(vc);__gwt_stylesLoaded[uc]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+uc);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Ac]){var a=n.createElement(vc);__gwt_stylesLoaded[Ac]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Ac);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Bc]){var a=n.createElement(vc);__gwt_stylesLoaded[Bc]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Bc);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Cc]){var a=n.createElement(vc);__gwt_stylesLoaded[Cc]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Cc);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Dc]){var a=n.createElement(vc);__gwt_stylesLoaded[Dc]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Dc);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Ec]){var a=n.createElement(vc);__gwt_stylesLoaded[Ec]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Ec);n.getElementsByTagName(zc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(Fc,T,false)}if(S){clearInterval(S)}}}
if(n.addEventListener){n.addEventListener(Fc,function(){O();T()},false)}var S=setInterval(function(){if(/loaded|complete/.test(n.readyState)){O();T()}},50);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:bb});o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:$b,millis:(new Date).getTime(),type:Y});n.write(Gc)}
javaleague2();